[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[colors]
draw_bold_text_with_bright_colors = true

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.padding]
x = 6
y = 6

[keyboard]
bindings = [
  { key = "Left", mods = "Control", chars = "\u001BB" },
  { key = "Right", mods = "Control", chars = "\u001BF" }
]
